name: Renovate

on:
  schedule:
    # Run daily at 02:00 UTC.
    - cron: "0 2 * * *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  renovate:
    name: Renovate
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v7

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v46.1.20
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
          configurationFile: renovate.json